name: Release Please

on:
  workflow_run:
    workflows: ["Rust CI"] # Name of the CI workflow file (rust.yml)
    types:
      - completed
    branches:
      - master

  # Keep workflow_call if needed for other workflows to get release info
  workflow_call:
    outputs:
      release_created:
        description: "Whether a release was created by release-please"
        value: ${{ jobs.release-please.outputs.created }}

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    name: Run release-please
    runs-on: ubuntu-latest
    # Add condition to only run if the triggering workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      # Checkout the code from the commit that triggered the Rust CI workflow
      - uses: actions/checkout@v4
        with:
          # Use the SHA from the workflow_run event
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: rust
          # Optionally configure package name if Cargo.toml is not at the root
          # package-name: your-crate-name
          # You might need a PAT instead of GITHUB_TOKEN if you hit permission issues
          # token: ${{ secrets.YOUR_PAT }}

  publish:
    name: Publish to crates.io
    needs: release-please
    runs-on: ubuntu-latest
    # This job also already checks if release-please created a release.
    if: needs.release-please.outputs.created == 'true'
    environment: # Optional: Use GitHub Environments for added security/control
      name: crates_io
      url: https://crates.io/crates/buup # Replace 'buup' if your crate name differs
    steps:
      - uses: actions/checkout@v4
        with:
          # Checkout the specific tag created by release-please
          ref: ${{ needs.release-please.outputs.tag_name }}

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      # If your project is a workspace, you might need to publish members individually
      # or use a tool like `cargo-workspaces` or `katyo/publish-crates` here.
      # For a single crate:
      - name: Publish crate
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        env:
          # CARGO_REGISTRY_TOKEN needs to be set in GitHub Secrets
          # (or Environment Secrets if using GitHub Environments)
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish-gh-pages:
    name: Publish buup_web app to GitHub Pages
    needs: release-please
    runs-on: ubuntu-latest
    if: needs.release-please.outputs.created == 'true'
    permissions:
      contents: write # Needed to push to gh-pages branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0

      - name: Run Dioxus Deploy Action
        working-directory: ./buup_web
        run: |
          # This will run the equivalent of the Dioxus deploy action in the buup_web directory
          cargo install dioxus-cli
          dx build --release

      - name: Copy specific assets to public folder for GitHub Pages
        run: |
          cp buup_web/assets/sitemap.xml target/dx/buup_web/release/web/public/sitemap.xml
          cp buup_web/assets/robots.txt target/dx/buup_web/release/web/public/robots.txt

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/dx/buup_web/release/web/public
          branch: gh-pages

  build-and-upload-binaries:
    name: Build & Upload Binaries
    needs: release-please
    if: needs.release-please.outputs.created == 'true'
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write # Needed to upload release assets
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_ext: tar.gz
            binary_ext: ""
          - os: macos-latest # Should default to x86_64 runner
            target: x86_64-apple-darwin
            asset_ext: tar.gz
            binary_ext: ""
          - os: macos-latest # M1/M2 Macs
            target: aarch64-apple-darwin
            asset_ext: tar.gz
            binary_ext: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_ext: zip
            binary_ext: .exe

    steps:
      - name: Checkout code for the release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.release-please.outputs.tag_name }}

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build binary
        run: cargo build --release --bin buup --target ${{ matrix.target }}

      - name: Prepare artifacts (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          strip buup || true # Try stripping, ignore if fails
          tar czf ../../../buup-${{ needs.release-please.outputs.tag_name }}-${{ matrix.target }}.tar.gz buup
          cd ../../..
        shell: bash

      - name: Prepare artifacts (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          # Use Compress-Archive from PowerShell standard library
          Compress-Archive -Path buup.exe -DestinationPath ../../../buup-${{ needs.release-please.outputs.tag_name }}-${{ matrix.target }}.zip
          cd ../../..
        shell: pwsh # Use PowerShell

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release-please.outputs.upload_url }}
          asset_path: ./buup-${{ needs.release-please.outputs.tag_name }}-${{ matrix.target }}.${{ matrix.asset_ext }}
          asset_name: buup-${{ needs.release-please.outputs.tag_name }}-${{ matrix.target }}.${{ matrix.asset_ext }}
          asset_content_type: application/zip # Use application/zip consistently
